# Generated by Django 5.1.7 on 2025-03-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("bill_names", models.CharField(max_length=255)),
                ("extras", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
