# Generated by Django 5.1.7 on 2025-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0002_billfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="bill_names",
            field=models.CharField(
                help_text="Enter bill names separated by + (e.g., GASPER+JANEZ+MATEJA)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="extras",
            field=models.TextField(
                blank=True,
                help_text="Optional extra information separated by commas",
                null=True,
            ),
        ),
    ]
