# Generated by Django 5.1.7 on 2025-03-25 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0004_alter_billfile_file_alter_billfile_month_folder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Čas"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Informacija"),
                            ("WARNING", "Opozorilo"),
                            ("ERROR", "Napaka"),
                            ("SUCCESS", "Uspeh"),
                        ],
                        default="INFO",
                        max_length=10,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SYSTEM", "Sistem"),
                            ("USER", "Uporabnik"),
                        ],
                        default="SYSTEM",
                        max_length=10,
                        verbose_name="Kategorija",
                    ),
                ),
                ("message", models.TextField(verbose_name="Sporočilo")),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="Podrobnosti"),
                ),
            ],
            options={
                "verbose_name": "Dnevniški zapis",
                "verbose_name_plural": "Dnevniški zapisi",
                "ordering": ["-timestamp"],
            },
        ),
    ]
